'use client'
import { hydrateRoot } from 'react-dom/client';

import { usePathname, useSearchParams } from 'next/navigation'
import './globals.css'
import { Inter } from 'next/font/google'


import MainHeader from './components/layout/main-header'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname()
  const searchParams = useSearchParams()

  const excludeHeader = pathname.startsWith('/admin')

  return (
    <html lang="en">
     
      <body className={inter.className}> {!excludeHeader && <MainHeader />}{children}</body>
    </html>
  )
}

