import "server-only"
import { hydrateRoot } from 'react-dom/client';


import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from "./utils/providers";
import Footer from './components/layout/footer'
import MainHeader from './components/layout/main-header'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

//   const pathname = usePathname()
//   const searchParams = useSearchParams()

//   const excludeHeader = pathname.startsWith('/admin')
//  const excludeHeader1 = pathname.startsWith('/blog')

  return (
    <html lang="en">
     
      <body className={inter.className} >       
{/* {!(excludeHeader ) && <MainHeader />} */}
<Providers children />
{children}


  {/* {!(excludeHeader ) && <Footer />} */}
</body>
    </html>
  )
}



